added few sanity checks to `Dockerfile`

diff --git a/docker_environment/Dockerfile b/docker_environment/Dockerfile
--- a/docker_environment/Dockerfile
+++ b/docker_environment/Dockerfile
@@ -7,6 +7,7 @@ ARG DEBIAN_FRONTEND=noninteractive
 ENV TERM=xterm-color
 ENV COLORTERM=truecolor
 
+
 # >>>>>> Configure Locale >>>>>>
 RUN set -ex \
     && apt-get update --fix-missing \
@@ -26,26 +27,28 @@ ENV LC_ALL=en_US.UTF-8
 ENV LC_CTYPE=UTF-8
 # <<<<<< Configure Locale <<<<<<
 
-# We set the user as "root" during the building process
+
+# Set the user as "root" during the building process
 USER root
 EXPOSE 8888
 
+
+# >>>>>> Install Python >>>>>>
 RUN set -ex \
     && apt-get update \
-    # Configure Python3.9 repo on the system
+    # configure Python3.9 repo on the system
     && apt install -y software-properties-common \
     && add-apt-repository ppa:deadsnakes/ppa \
     # ensure to remove package's state information (it can be recreated with 'apt-get update')
     && rm -rf /var/lib/apt/lists/*
 
-# Install python3.9
 RUN set -ex \
     && apt-get update \
     && apt-get install -y --no-install-recommends \
-    # install Python3 (and pip3)
+    # install Python3.9 (and pip3)
     python3.9 \
     python3-pip \
-    # Create symbolic links:
+    # create symbolic links:
     #   python -> python3
     #   pip -> pip3
     && ln -sfn /usr/bin/python3.9 /usr/bin/python \
@@ -57,7 +60,6 @@ RUN set -ex \
     # ensure to remove package's state information (it can be recreated with 'apt-get update')
     && rm -rf /var/lib/apt/lists/*
 
-# We install needed dependencies
 RUN set -ex \
     && apt-get update \
     && apt-get install -yq \
@@ -68,16 +70,17 @@ RUN set -ex \
     # python3 \
     # python3-pip \
     python3-venv \
-    # install data transfer tool (and other packages)
+    # install data transfer (and other) packages
     ca-certificates curl gnupg2 \
-    wget \
-    nano \
+    # install packages required for building the docker image
+    rsync \
+    # install utility packages
+    htop nano wget \
+    # install misc packages
     bzip2 \
-    sudo \
     fonts-liberation \
     run-one \
-    htop \
-    rsync \
+    sudo \
     # sanity checks
     && pip --version \
     && pip3 --version \
@@ -86,11 +89,12 @@ RUN set -ex \
 
 RUN set -ex \
     # upgrade 'pip', 'setuptools', 'wheel'
-    #   pip==21.1.3 setuptools==57.2.0 wheel==0.33.6
     && python -m pip install --no-cache-dir --upgrade pip setuptools wheel \
     # && pip install --no-cache-dir --upgrade setuptools wheel \
     # sanity checks
     && python -m pip list | grep -iE '^pip|^setuptools|^wheel'
+# <<<<<< Install Python <<<<<<
+
 
 # >>>>>> Install Poetry >>>>>>
 RUN set -ex \
@@ -98,55 +102,65 @@ RUN set -ex \
     && apt-get install -y \
     # install data transfer tool (and other required packages)
     ca-certificates curl gnupg2 \
-    # Download poetry installer
+    # download poetry installer
     && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -o get-poetry.py \
-    # Install poetry
+    # install poetry
     && python3 get-poetry.py --version 1.1.10 \
     # remove unnecessary files
     # && rm -rf get-poetry.py \
     # ensure to remove package's state information (it can be recreated with 'apt-get update')
     && rm -rf /var/lib/apt/lists/*
 
+# Add poetry to the `PATH` environment variable
 ENV PATH="/root/.poetry/bin:$PATH"
 
 RUN set -ex \
-    # Tell poetry to install everything on system's python
+    # sanity checks
+    && poetry --version \
+    # tell poetry to install everything on system's python
     && poetry config virtualenvs.create false
-# <<<<<< Install Poetry  <<<<<<
+# <<<<<< Install Poetry <<<<<<
 
-# We set the current working directory
+
+# Set the current working directory
 WORKDIR /tmp
 
-# We copy files from the local folder to the working directory
+# Copy files from the local folder to the working directory
 COPY . .
 
-# We define some PATHs arguments
-ARG PATH_TO_EXAMPLES=lib/teselagen/examples/
-ARG PATH_TO_MODULE_REQUIREMENTS=lib/requirements.txt
-ARG PATH_TO_EXAMPLES_REQUIREMENTS=lib/teselagen/examples/requirements.txt
 
-# >>>>>> Install TeselaGen Library >>>>>>
+# >>>>>> Install teselagen Library >>>>>>
 RUN set -ex \
-    # Poetry installations are not editable
+    # poetry installations are not editable
     && cd lib/ \
     && POETRY_VIRTUALENVS_CREATE=false poetry install \
-    && cd ..
-# >>>>>> Install TeselaGen Library >>>>>>
+    && cd .. \
+    # sanity checks
+    && python3 -c "import teselagen" \
+    && python3 -c "import teselagen; print('teselagen version: ', teselagen.__version__)"
+# >>>>>> Install teselagen Library >>>>>>
 
-# Generate Jupyter Config
+
+# >>>>>> Generate Jupyter Config >>>>>>
 ENV PATH="~/.local/bin/jupyter-notebook:$PATH"
 RUN set -ex \
     && jupyter notebook --generate-config
+# >>>>>> Generate Jupyter Config >>>>>>
+
 
 # # >>>>>> Install Jupyter Extensions >>>>>>
-# RUN set -x \
-#     pip install jupyter_contrib_nbextensions \
+# RUN set -ex \
+#     && pip install jupyter_contrib_nbextensions \
 #     && jupyter contrib nbextension install --system \
 #     && jupyter nbextensions_configurator enable --user
 # # <<<<<< Install Jupyter Extensions <<<<<<
 
-# After the installation, we copy the examples folder to the home directory and then we delete the content of the
-# working directory that was used for building and installing everything.
+
+# >>>>>> Clean Up >>>>>>
+ARG PATH_TO_EXAMPLES=lib/teselagen/examples/
+ARG PATH_TO_EXAMPLES_REQUIREMENTS=lib/teselagen/examples/requirements.txt
+
+# After the installation, we copy the examples folder to the home directory
 RUN set -ex \
     && rsync ${PATH_TO_EXAMPLES} /home/ \
     --human-readable \
@@ -156,20 +170,27 @@ RUN set -ex \
     --recursive \
     --exclude "*requirements.txt"
 
+# Then we delete the content of the working directory that was used for building and installing everything.
 # Delete all from the local folder, except the file with the given name.
 # RUN find . \! -name "*start.sh" -delete
+# >>>>>> Clean Up >>>>>>
 
-# Set on bash start script
+
 RUN set -ex \
+    # set on bash start script
     && echo source "/tmp/on_bash_start.sh" >> ~/.bashrc \
+    # provide proper permissions
     && chmod 775 /tmp/on_bash_start.sh
 
-# Entry point
+
+# >>>>>> Entrypoint & Command >>>>>>
 RUN set -ex \
+    # provide proper permissions
     && chmod +x on_start.sh
 
-# And we set the "home" as the default working directory
+# Set the default working directory for the container
 WORKDIR /home/
 
 ENTRYPOINT ["/tmp/on_start.sh"]
 # ENTRYPOINT ["tail", "-f", "/dev/null"]
+# <<<<<< Entrypoint & Command <<<<<<
